### ISSUE TITLE
Logo orange/green versions by default and option to upload your own

### ISSUE THREAD

**Issue by sanchaz** [sanchaz/bitcoin-cash-payments-for-woocommerce#4]
The plugin should come by default with an orange and a green logo for the checkout option.
However BCH is permissionless so who are we to impose on the logo used? So there should also be an option to upload your own design or point to a url where the design is.

**Comment by zanza321** [comment]
Good idea, but maybe complex to setup.  Maybe just include 2-3 choices built into the plugin, and people can select which one they prefer to use.  This might be much easier to add in?

**Comment by sanchaz** [comment]
I think once we give multiple options it will probably be easy to just provide an input box for a url. Anyway I will look at this when I have some more time.

**Comment by acidsploit** [comment]
An upload your own option would be nice to have.

Anyway, as promised, some options:


![logo](https://i.imgur.com/D8cvvym.png"Orange")
https://i.imgur.com/D8cvvym.png

![logo](https://i.imgur.com/VnsnvKy.png"Green")
https://i.imgur.com/VnsnvKy.png

**Comment by sanchaz** [comment]
I've done these changes. You can also upload more to the folder if you don't like these, no code changes needed, it will automatically find them.
It's currently not merged but you can find it in this branch, please use only for testing until it is merged to master, unless you test it yourself before.
https://github.com/sanchaz/bitcoin-cash-payments-for-woocommerce/tree/selectable_checkout_icon

**Comment by sanchaz** [comment]
https://github.com/sanchaz/bitcoin-cash-payments-for-woocommerce/releases/tag/4.18
