### ISSUE TITLE
cashaddr not showing up?

### ISSUE THREAD

**Issue by zanza321** [sanchaz/bitcoin-cash-payments-for-woocommerce#5]
HI, I just installed the latest version, and there seems to be some problems generating the cashaddr portion of the checkout, so the plugin just ingores it.

See screenshot here for the completed order page:

![untitled](https://user-images.githubusercontent.com/28131200/35248345-9f46c458-ff82-11e7-82ff-93066ef67f27.png)

**Comment by sanchaz** [comment]
You did a clean install? or upgrade?

**Comment by zanza321** [comment]
I coped the files through FTP.  I will remove all and do a reinstall now and check it.

**Comment by sanchaz** [comment]
you need to deactivate the plugin and activate again, so it makes some changes to the table.

**Comment by zanza321** [comment]
great, working now !  thanks! :D:D

**Comment by sanchaz** [comment]
:) cool, closing the issue. Whenever you're upgrading plugins manually make sure to deactivate them and then reactivate.
