### ISSUE TITLE
QR code and Payment address needs to be at the top of the check out page

### ISSUE THREAD

**Issue by barbarbarbaros** [sanchaz/bitcoin-cash-payments-for-woocommerce#6]
Currently a bunch of text is displayed after user gets to the payment page, and qr code and the bch address is displayed a little bit below that. I don't know if this is about the plugin or woocommerce, but I think users would want to see the QR code and the address first.

This is my first time using github, so I don't really know the formatting of submitting new issues. Apologies in advance.

**Comment by sanchaz** [comment]
hey srry it took so long. I've briefly looked into this, looks like this has to do with woocommerce or the theme you are using.
I think the alternative here is to redirect to your own thank you page.
See here https://nicola.blog/2015/01/21/customize-the-thank-you-page-in-woocommerce/
not sure this is the best way to approach it. But it's a start.
